// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: hRiCxzQw6uAnAF5XWxoyQB
// Component: llMzhtmToEkM
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button2 from "../../Button2"; // plasmic-import: ebECvvG35vI/component
import Slider from "react-slick"; // plasmic-import: HOQUyOpClJ/codeComponent
import { Animationdiv } from "../../../../../components/Animationdiv"; // plasmic-import: Tivf36IHsR/codeComponent
import { useScreenVariants as useScreenVariantsgFNqF1JbOkX5P } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: gFNqF1JBOkX5P/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_shopapp.module.css"; // plasmic-import: hRiCxzQw6uAnAF5XWxoyQB/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: llMzhtmToEkM/css
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: e8GTkCTt7n-/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: rScP3g1V7mD/icon
import Icon14Icon from "./icons/PlasmicIcon__Icon14"; // plasmic-import: 4QbprynNltN/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: vvt2medwZhY/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: NurqsErWanI/icon
import Icon28Icon from "./icons/PlasmicIcon__Icon28"; // plasmic-import: XzxmUSMgO3w/icon
import imageZRtu7Rt2C from "./images/image.svg"; // plasmic-import: z_rtu7Rt2_C/picture
import adamHighlyDetailedFuturisticCarsRacingInSpaceLeagueOf633D1D7490C14Fd085B6Fc872411A60CpngVZacuhFam from "./images/adamHighlyDetailedFuturisticCarsRacingInSpaceLeagueOf633D1D7490C14Fd085B6Fc872411A60Cpng.png"; // plasmic-import: vZacuhFam/picture
import adamMacawFullColorPaintingFfff4C98C0Ce45AaB6Ee73A7760E6677PngOu8VP2FN3 from "./images/adamMacawFullColorPaintingFfff4C98C0Ce45AaB6Ee73A7760E6677Png.png"; // plasmic-import: ou8vP2fN3/picture
import adamTShirtDesignLionelMessiFullBodyFromBehindDeklart4Ff53343B64F427792C3D27587979816PngOo7V3Lfc from "./images/adamTShirtDesignLionelMessiFullBodyFromBehindDeklart4Ff53343B64F427792C3D27587979816Png.png"; // plasmic-import: Oo7V3lfc_/picture
import adamSketchOfAManWalkingInTheRainBlackwhiteB848Dd528C5943F9A80709695E8C0Bc5PngQyGqZtUne from "./images/adamSketchOfAManWalkingInTheRainBlackwhiteB848Dd528C5943F9A80709695E8C0Bc5Png.png"; // plasmic-import: qyGqZtUne/picture

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsgFNqF1JbOkX5P()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        {true ? (
          <div
            data-plasmic-name={"root"}
            data-plasmic-override={overrides.root}
            data-plasmic-root={true}
            data-plasmic-for-node={forNode}
            className={classNames(
              projectcss.all,
              projectcss.root_reset,
              projectcss.plasmic_default_styles,
              projectcss.plasmic_mixins,
              sty.root
            )}
          >
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox___4EgTg)}>
                {true ? (
                  <div
                    data-plasmic-name={"logoStack"}
                    data-plasmic-override={overrides.logoStack}
                    className={classNames(projectcss.all, sty.logoStack)}
                  >
                    {true ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.columns___8A3M
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__znpkk
                          )}
                        >
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__aPxWj
                            )}
                          >
                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__aL50G
                              )}
                            >
                              <p.PlasmicImg
                                alt={""}
                                className={classNames(sty.img__s3Hwg)}
                                displayHeight={"40px"}
                                displayMaxHeight={"none"}
                                displayMaxWidth={"none"}
                                displayMinHeight={"0"}
                                displayMinWidth={"0"}
                                displayWidth={"40px"}
                                src={{
                                  src: imageZRtu7Rt2C,
                                  fullWidth: 150,
                                  fullHeight: 150,
                                  aspectRatio: 1
                                }}
                              />

                              <p.Stack
                                as={"div"}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__eGm8K
                                )}
                              >
                                <Button2
                                  className={classNames(
                                    "__wab_instance",
                                    sty.button2__vsMt3
                                  )}
                                  color={"clear"}
                                  endIcon={
                                    <Icon38Icon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__gLz5J
                                      )}
                                      role={"img"}
                                    />
                                  }
                                  startIcon={
                                    <ChecksvgIcon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__eBbaM
                                      )}
                                      role={"img"}
                                    />
                                  }
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text___7Wdm0
                                    )}
                                  >
                                    {"AD-IT"}
                                  </div>
                                </Button2>

                                <Button2
                                  className={classNames(
                                    "__wab_instance",
                                    sty.button2__sbKkj
                                  )}
                                  color={"clear"}
                                  endIcon={
                                    <Icon38Icon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__wYXoo
                                      )}
                                      role={"img"}
                                    />
                                  }
                                  startIcon={
                                    <ChecksvgIcon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__ynHu1
                                      )}
                                      role={"img"}
                                    />
                                  }
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__nu5Fc
                                    )}
                                  >
                                    {"GameZone"}
                                  </div>
                                </Button2>

                                <Button2
                                  className={classNames(
                                    "__wab_instance",
                                    sty.button2__wx7WN
                                  )}
                                  color={"clear"}
                                  endIcon={
                                    <Icon38Icon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__qkxad
                                      )}
                                      role={"img"}
                                    />
                                  }
                                  startIcon={
                                    <ChecksvgIcon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__fjTCz
                                      )}
                                      role={"img"}
                                    />
                                  }
                                >
                                  <div
                                    data-plasmic-name={"blog"}
                                    data-plasmic-override={overrides.blog}
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.blog
                                    )}
                                  >
                                    {"Blog"}
                                  </div>
                                </Button2>

                                <Button2
                                  className={classNames(
                                    "__wab_instance",
                                    sty.button2__zZoLy
                                  )}
                                  color={"clear"}
                                  endIcon={
                                    <Icon38Icon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__tbjpd
                                      )}
                                      role={"img"}
                                    />
                                  }
                                  startIcon={
                                    <ChecksvgIcon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__niX3
                                      )}
                                      role={"img"}
                                    />
                                  }
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__aekh9
                                    )}
                                  >
                                    {"community"}
                                  </div>
                                </Button2>

                                <Button2
                                  className={classNames(
                                    "__wab_instance",
                                    sty.button2___5OGy7
                                  )}
                                  color={"clear"}
                                  endIcon={
                                    <Icon38Icon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__t4GqX
                                      )}
                                      role={"img"}
                                    />
                                  }
                                  startIcon={
                                    <ChecksvgIcon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__xEagY
                                      )}
                                      role={"img"}
                                    />
                                  }
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__yppKs
                                    )}
                                  >
                                    {"FAQ"}
                                  </div>
                                </Button2>

                                <Button2
                                  className={classNames(
                                    "__wab_instance",
                                    sty.button2__on0E
                                  )}
                                  endIcon={
                                    <Icon38Icon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__wf7T2
                                      )}
                                      role={"img"}
                                    />
                                  }
                                  startIcon={
                                    <ChecksvgIcon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__xvwEo
                                      )}
                                      role={"img"}
                                    />
                                  }
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__zc2Ha
                                    )}
                                  >
                                    {"Sign up"}
                                  </div>
                                </Button2>
                              </p.Stack>

                              {false ? (
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__pu8KE
                                  )}
                                >
                                  <button
                                    data-plasmic-name={"button"}
                                    data-plasmic-override={overrides.button}
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.button,
                                      projectcss.__wab_text,
                                      sty.button
                                    )}
                                  >
                                    {"Sign up"}
                                  </button>

                                  {true ? (
                                    <Button2
                                      className={classNames(
                                        "__wab_instance",
                                        sty.button2__ahJ1F
                                      )}
                                      color={"clear"}
                                      endIcon={
                                        <Icon38Icon
                                          className={classNames(
                                            projectcss.all,
                                            sty.svg__dl69G
                                          )}
                                          role={"img"}
                                        />
                                      }
                                      startIcon={
                                        <ChecksvgIcon
                                          className={classNames(
                                            projectcss.all,
                                            sty.svg__jnBra
                                          )}
                                          role={"img"}
                                        />
                                      }
                                    >
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.__wab_text,
                                          sty.text__fg8Sn
                                        )}
                                      >
                                        {"Log in"}
                                      </div>
                                    </Button2>
                                  ) : null}
                                </div>
                              ) : null}
                            </p.Stack>
                          </p.Stack>
                        </div>
                      </div>
                    ) : null}
                  </div>
                ) : null}
                {true ? (
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"foreground2"}
                    data-plasmic-override={overrides.foreground2}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.foreground2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ubp6E
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ textDecoration: "underline" }}
                        >
                          {"Lorem ipsum doller summit"}
                        </span>
                      </React.Fragment>
                    </div>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__jn7Pv)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__d5Tge
                        )}
                      >
                        {
                          "Orci dui condimentum rutrum laoreet hac purus porta sem sem a vivamus a posuere vel molestie."
                        }
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__wiBU)}
                    >
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__zLooL
                        )}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__c8Gxm
                            )}
                            role={"img"}
                          />
                        }
                        startIcon={
                          <ChecksvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__wKyK
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___6Y2Vg
                          )}
                        >
                          {"Start now ->"}
                        </div>
                      </Button2>

                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__wg27D
                        )}
                        color={"clear"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___7NQCe
                            )}
                            role={"img"}
                          />
                        }
                        startIcon={
                          <ChecksvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__jhqUm
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__cfLY
                          )}
                        >
                          {"Learn more…"}
                        </div>
                      </Button2>
                    </p.Stack>
                  </p.Stack>
                ) : null}
              </div>
            ) : null}
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox___2L62C)}>
                <div
                  data-plasmic-name={"asdfasdfasdfasdfasdf"}
                  data-plasmic-override={overrides.asdfasdfasdfasdfasdf}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.asdfasdfasdfasdfasdf
                  )}
                >
                  {"Tech-Product-Slide"}
                </div>
              </div>
            ) : null}
            {true ? (
              <Slider
                data-plasmic-name={"slider"}
                data-plasmic-override={overrides.slider}
                accessibility={true}
                adaptiveHeight={false}
                autoplay={true}
                autoplaySpeed={500}
                centerMode={true}
                centerPadding={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "10px"
                    : "50px"
                }
                className={classNames("__wab_instance", sty.slider)}
                dots={true}
                draggable={true}
                easing={"linear"}
                fade={false}
                focusOnSelect={false}
                pauseOnDotsHover={false}
                pauseOnFocus={false}
                pauseOnHover={true}
                slidesToScroll={1}
                slidesToShow={3}
                speed={1000}
                swipeToSlide={true}
                variableWidth={false}
                vertical={false}
              >
                {true ? (
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__wtkFk)}
                    displayHeight={"854px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"1257px"}
                    src={{
                      src: adamHighlyDetailedFuturisticCarsRacingInSpaceLeagueOf633D1D7490C14Fd085B6Fc872411A60CpngVZacuhFam,
                      fullWidth: 1024,
                      fullHeight: 1024,
                      aspectRatio: undefined
                    }}
                  />
                ) : null}

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__d0Xba)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"921px"}
                  src={{
                    src: adamMacawFullColorPaintingFfff4C98C0Ce45AaB6Ee73A7760E6677PngOu8VP2FN3,
                    fullWidth: 1024,
                    fullHeight: 1024,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__fOb2O)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"921px"}
                  src={{
                    src: adamTShirtDesignLionelMessiFullBodyFromBehindDeklart4Ff53343B64F427792C3D27587979816PngOo7V3Lfc,
                    fullWidth: 1024,
                    fullHeight: 1024,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__nskU)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  src={{
                    src: adamSketchOfAManWalkingInTheRainBlackwhiteB848Dd528C5943F9A80709695E8C0Bc5PngQyGqZtUne,
                    fullWidth: 1024,
                    fullHeight: 1024,
                    aspectRatio: undefined
                  }}
                />
              </Slider>
            ) : null}

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__lz1Ar)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__nYadd)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zlI8U
                  )}
                >
                  {"Game Zone"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dne1R
                  )}
                >
                  {
                    "Orci dui condimentum rutrum laoreet hac purus porta sem sem a vivamus a posuere vel molestie."
                  }
                </div>

                <Button2
                  className={classNames("__wab_instance", sty.button2___70EOy)}
                  endIcon={
                    <Icon38Icon
                      className={classNames(projectcss.all, sty.svg__vLsEn)}
                      role={"img"}
                    />
                  }
                  startIcon={
                    <ChecksvgIcon
                      className={classNames(projectcss.all, sty.svg__onPr)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lwHbH
                    )}
                  >
                    {"Start now ->"}
                  </div>
                </Button2>
              </p.Stack>
            </p.Stack>

            <div className={classNames(projectcss.all, sty.freeBox__tkNl0)}>
              <div className={classNames(projectcss.all, sty.freeBox__tjk1N)} />

              <p.Stack
                as={"div"}
                data-plasmic-name={"foreground"}
                data-plasmic-override={overrides.foreground}
                hasGap={true}
                className={classNames(projectcss.all, sty.foreground)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__annzE)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox___2Eq9D)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__u6Vm
                      )}
                    >
                      {"Plan with appShop"}
                    </div>
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tjPlr
                    )}
                  >
                    {
                      "Nascetur nascetur ridiculus scelerisque adipiscing a nascetur varius sed eu a ad semper a est nec litora ante at orci rhoncus a varius auctor aliquam inceptos vestibulum ridiculus."
                    }
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__v6Beq)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mxDc)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___589Ut
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__cDfLm
                        )}
                      >
                        {"Starter"}
                      </div>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__rN4Q2
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__zXay
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ipnm1
                            )}
                          >
                            {"$"}
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__l1FbE
                            )}
                          >
                            {"8"}
                          </div>
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__osG9Q
                          )}
                        >
                          {"/month"}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__teF6J)}
                    />

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__lIyEd)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__yc5Ey
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__nvnrb
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__wdi9D
                            )}
                          >
                            <Icon14Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__ihfil
                              )}
                              role={"img"}
                            />
                          </div>

                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__sDv3T
                              )}
                            >
                              <Icon14Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__ox3ZW
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__cKZyL
                            )}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__oN98H
                                )}
                              >
                                {"Label"}
                              </div>
                            ) : null}

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__gri3Q
                              )}
                            >
                              {
                                "Vestibulum mollis odio dictum ultrices facilisis molestie vestibulum"
                              }
                            </div>
                          </p.Stack>
                        </p.Stack>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__wUg4H
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__iBkm7
                            )}
                          >
                            <Icon14Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg___9VYd7
                              )}
                              role={"img"}
                            />
                          </div>

                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__df4Py
                              )}
                            >
                              <Icon14Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___4DhMo
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___5Soav
                            )}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__wph4U
                                )}
                              >
                                {"Label"}
                              </div>
                            ) : null}

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__qKgpF
                              )}
                            >
                              {"Mus consequat a justo"}
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </p.Stack>

                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__zVFmi
                        )}
                        color={"white"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___9A06C
                            )}
                            role={"img"}
                          />
                        }
                        startIcon={
                          <ChecksvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__aSrjs
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__rYgH1
                          )}
                        >
                          {"Buy starter"}
                        </div>
                      </Button2>
                    </p.Stack>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__hCxY)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__lXui)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tZn4T
                        )}
                      >
                        {"Pro"}
                      </div>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___1SfBw
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___9OlI0
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__jvJnd
                            )}
                          >
                            {"$"}
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__oB7PE
                            )}
                          >
                            {"16"}
                          </div>
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zhWzp
                          )}
                        >
                          {"/month"}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__cpXz)}
                    />

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__zeXfr)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__wieG
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___2YPlX
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__vO2KO
                            )}
                          >
                            <Icon14Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__eKqnY
                              )}
                              role={"img"}
                            />
                          </div>

                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox___9Hqx8
                              )}
                            >
                              <Icon14Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__f82Wu
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__rPqS1
                            )}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__aeheq
                                )}
                              >
                                {"Label"}
                              </div>
                            ) : null}

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__uFam
                              )}
                            >
                              {
                                "Ligula primis mollis sem dignissim semper lectus parturient"
                              }
                            </div>
                          </p.Stack>
                        </p.Stack>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__vh7DP
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___9P3Tu
                            )}
                          >
                            <Icon14Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__qPxpV
                              )}
                              role={"img"}
                            />
                          </div>

                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__bBbN
                              )}
                            >
                              <Icon14Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__yvNfV
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__gzGRq
                            )}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___7ScJ8
                                )}
                              >
                                {"Label"}
                              </div>
                            ) : null}

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__diCx6
                              )}
                            >
                              {"A curabitur dignissim pharetra porta suscipit"}
                            </div>
                          </p.Stack>
                        </p.Stack>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__vVcTo
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__pXzM
                            )}
                          >
                            <Icon14Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg___86Po6
                              )}
                              role={"img"}
                            />
                          </div>

                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__kqqX
                              )}
                            >
                              <Icon14Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__xZzoH
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__aOcUb
                            )}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__lMx6Q
                                )}
                              >
                                {"Label"}
                              </div>
                            ) : null}

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__xzUdG
                              )}
                            >
                              {
                                "Condimentum diam a et sapien praesent potenti torquent a eros"
                              }
                            </div>
                          </p.Stack>
                        </p.Stack>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__sripw
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___3HcR
                            )}
                          >
                            <Icon14Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__yYm4H
                              )}
                              role={"img"}
                            />
                          </div>

                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__fc2A1
                              )}
                            >
                              <Icon14Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__pcPi6
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__mjqxy
                            )}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__rfsYk
                                )}
                              >
                                {"Label"}
                              </div>
                            ) : null}

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___5LMaC
                              )}
                            >
                              {"Conubia in hac eu elementum sodales"}
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </p.Stack>

                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__xfz1R
                        )}
                        color={"green"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__d5Att
                            )}
                            role={"img"}
                          />
                        }
                        startIcon={
                          <ChecksvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__mk2B6
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__rerdq
                          )}
                        >
                          {"Buy pro"}
                        </div>
                      </Button2>
                    </p.Stack>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__qNkSd)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__pE1Sx)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__sJpJg
                        )}
                      >
                        {"Team"}
                      </div>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__ywBj
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__oyy9U
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___9KZ0Q
                            )}
                          >
                            {"$"}
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___5C25V
                            )}
                          >
                            {"10"}
                          </div>
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__gEJkM
                          )}
                        >
                          {"/member"}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__l5Qgl)}
                    />

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__uISh5)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___0EIjp
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__wSXpv
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__czwai
                            )}
                          >
                            <Icon14Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__oCmnz
                              )}
                              role={"img"}
                            />
                          </div>

                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__egGvt
                              )}
                            >
                              <Icon14Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___8XJg
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__nF53W
                            )}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__g0T2I
                                )}
                              >
                                {"Label"}
                              </div>
                            ) : null}

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__rDi69
                              )}
                            >
                              {"Ad nam curae a potenti platea"}
                            </div>
                          </p.Stack>
                        </p.Stack>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__cYbsj
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__qqb8
                            )}
                          >
                            <Icon14Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__rXrg
                              )}
                              role={"img"}
                            />
                          </div>

                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__dpuzl
                              )}
                            >
                              <Icon14Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___6I4Cl
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__qrpqK
                            )}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__rAui
                                )}
                              >
                                {"Label"}
                              </div>
                            ) : null}

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__hv7Ok
                              )}
                            >
                              {
                                "A adipiscing scelerisque pretium consectetur sem"
                              }
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </p.Stack>

                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__lkN1N
                        )}
                        color={"white"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___4EEyk
                            )}
                            role={"img"}
                          />
                        }
                        startIcon={
                          <ChecksvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__fkpNz
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wpgVg
                          )}
                        >
                          {"Buy team"}
                        </div>
                      </Button2>
                    </p.Stack>
                  </div>
                </p.Stack>
              </p.Stack>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__xnEes)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__uuc3L)}
              >
                <div className={classNames(projectcss.all, sty.column__wwJyi)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__znrE)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__fCkjq)}
                      displayHeight={"40px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"40px"}
                      src={{
                        src: imageZRtu7Rt2C,
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__cP18L)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ueBpM
                        )}
                      >
                        {"Connect with us"}
                      </div>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___4XMhB
                        )}
                      >
                        <Icon3Icon
                          className={classNames(projectcss.all, sty.svg__nLnzy)}
                          role={"img"}
                        />

                        <Icon2Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___4QvGa
                          )}
                          role={"img"}
                        />

                        <Icon28Icon
                          className={classNames(projectcss.all, sty.svg__eciFu)}
                          role={"img"}
                        />
                      </p.Stack>
                    </p.Stack>
                  </p.Stack>
                </div>

                <div className={classNames(projectcss.all, sty.column__zhwqq)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__dUl02)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___4IyOm
                      )}
                    >
                      {"Product"}
                    </div>

                    <Button2
                      className={classNames(
                        "__wab_instance",
                        sty.button2__ts1Lx
                      )}
                      color={"clear"}
                      endIcon={
                        <Icon38Icon
                          className={classNames(projectcss.all, sty.svg__kmSeR)}
                          role={"img"}
                        />
                      }
                      size={"minimal"}
                      startIcon={
                        <ChecksvgIcon
                          className={classNames(projectcss.all, sty.svg__g4Ybe)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kpNj
                        )}
                      >
                        {"Pricing"}
                      </div>
                    </Button2>

                    <Button2
                      className={classNames(
                        "__wab_instance",
                        sty.button2__wApoz
                      )}
                      color={"clear"}
                      endIcon={
                        <Icon38Icon
                          className={classNames(projectcss.all, sty.svg__gbze3)}
                          role={"img"}
                        />
                      }
                      size={"minimal"}
                      startIcon={
                        <ChecksvgIcon
                          className={classNames(projectcss.all, sty.svg__es3Tl)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zoH0Q
                        )}
                      >
                        {"Log in"}
                      </div>
                    </Button2>

                    <Button2
                      className={classNames(
                        "__wab_instance",
                        sty.button2__rGom
                      )}
                      color={"clear"}
                      endIcon={
                        <Icon38Icon
                          className={classNames(projectcss.all, sty.svg__yhezb)}
                          role={"img"}
                        />
                      }
                      size={"minimal"}
                      startIcon={
                        <ChecksvgIcon
                          className={classNames(projectcss.all, sty.svg__z1NUl)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__oxSin
                        )}
                      >
                        {"Integrations"}
                      </div>
                    </Button2>

                    <Button2
                      className={classNames(
                        "__wab_instance",
                        sty.button2__poxiZ
                      )}
                      color={"clear"}
                      endIcon={
                        <Icon38Icon
                          className={classNames(projectcss.all, sty.svg__e6U94)}
                          role={"img"}
                        />
                      }
                      size={"minimal"}
                      startIcon={
                        <ChecksvgIcon
                          className={classNames(projectcss.all, sty.svg__rqsH)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__b5YRh
                        )}
                      >
                        {"Insights"}
                      </div>
                    </Button2>
                  </p.Stack>
                </div>

                <div className={classNames(projectcss.all, sty.column__xfOk0)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___1R9BB)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___9Sa1R
                      )}
                    >
                      {"Support"}
                    </div>

                    <Button2
                      className={classNames(
                        "__wab_instance",
                        sty.button2__e98H
                      )}
                      color={"clear"}
                      endIcon={
                        <Icon38Icon
                          className={classNames(projectcss.all, sty.svg__okYr1)}
                          role={"img"}
                        />
                      }
                      size={"minimal"}
                      startIcon={
                        <ChecksvgIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___1Jr0V
                          )}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__arq5J
                        )}
                      >
                        {"Documentation"}
                      </div>
                    </Button2>

                    <Button2
                      className={classNames(
                        "__wab_instance",
                        sty.button2__y29Ks
                      )}
                      color={"clear"}
                      endIcon={
                        <Icon38Icon
                          className={classNames(projectcss.all, sty.svg__tp4Rl)}
                          role={"img"}
                        />
                      }
                      size={"minimal"}
                      startIcon={
                        <ChecksvgIcon
                          className={classNames(projectcss.all, sty.svg__gPdSo)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___5LLua
                        )}
                      >
                        {"FAQs"}
                      </div>
                    </Button2>

                    <Button2
                      className={classNames(
                        "__wab_instance",
                        sty.button2__zNs66
                      )}
                      color={"clear"}
                      endIcon={
                        <Icon38Icon
                          className={classNames(projectcss.all, sty.svg__jVzSd)}
                          role={"img"}
                        />
                      }
                      size={"minimal"}
                      startIcon={
                        <ChecksvgIcon
                          className={classNames(projectcss.all, sty.svg__oSYjl)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wePa3
                        )}
                      >
                        {"Status"}
                      </div>
                    </Button2>
                  </p.Stack>
                </div>

                <div className={classNames(projectcss.all, sty.column__amacx)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__t9Qli)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lVabk
                      )}
                    >
                      {"Company"}
                    </div>

                    <Button2
                      className={classNames(
                        "__wab_instance",
                        sty.button2__mOzdw
                      )}
                      color={"clear"}
                      endIcon={
                        <Icon38Icon
                          className={classNames(projectcss.all, sty.svg__v7G1H)}
                          role={"img"}
                        />
                      }
                      size={"minimal"}
                      startIcon={
                        <ChecksvgIcon
                          className={classNames(projectcss.all, sty.svg__bJeZw)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qCtlg
                        )}
                      >
                        {"About"}
                      </div>
                    </Button2>

                    <Button2
                      className={classNames(
                        "__wab_instance",
                        sty.button2__el5Yg
                      )}
                      color={"clear"}
                      endIcon={
                        <Icon38Icon
                          className={classNames(projectcss.all, sty.svg__uTLzH)}
                          role={"img"}
                        />
                      }
                      size={"minimal"}
                      startIcon={
                        <ChecksvgIcon
                          className={classNames(projectcss.all, sty.svg__vfRo3)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mhzU
                        )}
                      >
                        {"Contact us"}
                      </div>
                    </Button2>

                    <Button2
                      className={classNames(
                        "__wab_instance",
                        sty.button2__w2S5S
                      )}
                      color={"clear"}
                      endIcon={
                        <Icon38Icon
                          className={classNames(projectcss.all, sty.svg__mY2Mv)}
                          role={"img"}
                        />
                      }
                      size={"minimal"}
                      startIcon={
                        <ChecksvgIcon
                          className={classNames(projectcss.all, sty.svg__bYg4X)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mwKhW
                        )}
                      >
                        {"Careers"}
                      </div>
                    </Button2>

                    <Button2
                      className={classNames(
                        "__wab_instance",
                        sty.button2__uEtjh
                      )}
                      color={"clear"}
                      endIcon={
                        <Icon38Icon
                          className={classNames(projectcss.all, sty.svg__buLl2)}
                          role={"img"}
                        />
                      }
                      size={"minimal"}
                      startIcon={
                        <ChecksvgIcon
                          className={classNames(projectcss.all, sty.svg__j6Uy2)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__oj6Y
                        )}
                      >
                        {"Media"}
                      </div>
                    </Button2>
                  </p.Stack>
                </div>
              </p.Stack>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__jRkLp)}>
              <Animationdiv
                className={classNames("__wab_instance", sty.animationdiv__tIbQ)}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv__vwvqA
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv__aO8YP
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv___9UPf
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv__fIvYw
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv__zcU36
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames("__wab_instance", sty.animationdiv__hcWx)}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv__bcXs3
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv___9XzUe
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv__zFuAo
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames("__wab_instance", sty.animationdiv__mo2O)}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv___4QTha
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv__szDni
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv___47NTa
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv__ldBc5
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv__zjk6I
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv___2N1Gu
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv__txN1M
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv__xwfZv
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames("__wab_instance", sty.animationdiv__zq0U)}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv__jro25
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv___276LC
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv__owFzK
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv__nw8PZ
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv__mWmLb
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv__wbksq
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv__rknEz
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv__hchCf
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv__pFpCq
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv___3BFtU
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv__kCzX8
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv___2Od7A
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv__qdndn
                )}
                name={" "}
              />

              <Animationdiv
                className={classNames(
                  "__wab_instance",
                  sty.animationdiv__uc4J2
                )}
                name={" "}
              />
            </div>
          </div>
        ) : null}
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "logoStack",
    "blog",
    "button",
    "foreground2",
    "asdfasdfasdfasdfasdf",
    "slider",
    "foreground"
  ],

  logoStack: ["logoStack", "blog", "button"],
  blog: ["blog"],
  button: ["button"],
  foreground2: ["foreground2"],
  asdfasdfasdfasdfasdf: ["asdfasdfasdfasdfasdf"],
  slider: ["slider"],
  foreground: ["foreground"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    logoStack: makeNodeComponent("logoStack"),
    blog: makeNodeComponent("blog"),
    button: makeNodeComponent("button"),
    foreground2: makeNodeComponent("foreground2"),
    asdfasdfasdfasdfasdf: makeNodeComponent("asdfasdfasdfasdfasdf"),
    slider: makeNodeComponent("slider"),
    foreground: makeNodeComponent("foreground"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
